defaultEntryPoints = ["http", "https"]
[entryPoints]
	[entryPoints.http]
	address = ":80"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]
	
[web]
address = ":8080"

# Enable Docker configuration backend.
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "s.dnam.dk"
watch = true
swarmmode = true
exposedbydefault = false


[acme]
email = "sorend@gmail.com"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
	[acme.httpChallenge]
	entryPoint = "http"
